name: webxhack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # Add this line for app icons

flutter:
  uses-material-design: true
  
  assets:
    - assets/

  # Add this flutter_launcher_icons configuration section
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/web_icon.png" 
